development: &development
  access_key_id: AKIAJA6KUBT6SWEGYV3Q
  secret_access_key: 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

production:
  access_key_id: AKIAIRKVQDTWT2NN4J4Q
  secret_access_key: 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

test:
  <<: *development
